export const appActionTypes = {
  TOGGLE_MENU: "TOGGLE_MENU",
  TOGGLE_LOADING: "TOGGLE_LOADING",
  TOGGLE_ADD_PRODUCT_MODAL: "TOGGLE_ADD_PRODUCT_MODAL",
  TOGGLE_UPDATE_PRODUCT_MODAL: "TOGGLE_UPDATE_PRODUCT_MODAL",
  SET_MESSAGE: "SET_MESSAGE",
  CHANGE_CAN_DELIVER: "CHANGE_CAN_DELIVER",
  SET_AVERAGE_TIME_BEFORE_DELIVERY: "SET_AVERAGE_TIME_BEFORE_DELIVERY",
};
