export const productActionTypes = {
  SET_ALL_PRODUCTS: "SET_ALL_PRODUCTS",
  SELECT_PRODUCT: "SELECT_PRODUCT",
  ADD_PRODUCT: "ADD_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  EDIT_PRODUCT: "EDIT_PRODUCT",
};
