export const productActionTypes = {
  SET_ALL_PRODUCTS: "SET_ALL_PRODUCTS",
  SELECT_PRODUCT: "SELECT_PRODUCT",
  ADD_PRODUCT: "ADD_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  SELECT_PRODUCT_TO_EDIT: "SELECT_PRODUCT_TO_EDIT",
};
